export type iconsLibrary = typeof iconsLibrary
import {
  GiBeerStein,
  GiTomato,
  GiPopcorn,
  GiCityCar,
  GiChiliPepper,
  GiCigarette,
  GiWaterBottle,
  GiWineBottle,
  GiWalk,
  GiPill,
  GiDeathStar,
  GiCycling,
  GiCakeSlice,
  GiBookCover,
  GiTeacher,
  GiTavernSign,
  GiToothbrush,
  GiNightSleep,
  GiBed,
  GiShoppingBag,
  GiMusicalScore,
  GiWeight,
  GiBasketballBall,
  GiGamepad,
  GiFilmStrip,
  GiTooth,
  GiTinker,
  GiMeditation,
  GiOrangeSlice,
  GiForkKnifeSpoon,
  GiGuitarBassHead,
  GiOpenFolder,
  GiNetworkBars,
  GiTakeMyMoney,
  GiPaintRoller,
  GiPalette,
} from 'react-icons/gi'

export const iconsLibrary = {
  habitIcons: [
    {
      id: 1,
      label: 'Water',
      icon: GiWaterBottle,
    },
    {
      id: 2,
      label: 'Beer',
      icon: GiBeerStein,
    },
    {
      id: 3,
      label: 'Tomato',
      icon: GiTomato,
    },
    {
      id: 4,
      label: 'Popcorn',
      icon: GiPopcorn,
    },
    {
      id: 5,
      label: 'Car',
      icon: GiCityCar,
    },
    {
      id: 6,
      label: 'Pepper',
      icon: GiChiliPepper,
    },
    {
      id: 7,
      label: 'Cigarette',
      icon: GiCigarette,
    },
    {
      id: 8,
      label: 'Wine',
      icon: GiWineBottle,
    },
    {
      id: 9,
      label: 'Walk',
      icon: GiWalk,
    },
    {
      id: 10,
      label: 'Pills',
      icon: GiPill,
    },
    {
      id: 11,
      label: 'Star',
      icon: GiDeathStar,
    },
    {
      id: 12,
      label: 'Cycling',
      icon: GiCycling,
    },
    {
      id: 13,
      label: 'Cake',
      icon: GiCakeSlice,
    },
    {
      id: 14,
      label: 'Book',
      icon: GiBookCover,
    },
    {
      id: 15,
      label: 'Teacher',
      icon: GiTeacher,
    },
    {
      id: 16,
      label: 'Tavern',
      icon: GiTavernSign,
    },
    {
      id: 17,
      label: 'Brush',
      icon: GiToothbrush,
    },
    {
      id: 18,
      label: 'Sleep',
      icon: GiNightSleep,
    },
    {
      id: 19,
      label: 'Bed',
      icon: GiBed,
    },
    {
      id: 20,
      label: 'Shopping',
      icon: GiShoppingBag,
    },
    {
      id: 21,
      label: 'Music',
      icon: GiMusicalScore,
    },
    {
      id: 22,
      label: 'Weight',
      icon: GiWeight,
    },
    {
      id: 23,
      label: 'Ball',
      icon: GiBasketballBall,
    },
    {
      id: 24,
      label: 'Game',
      icon: GiGamepad,
    },
    {
      id: 25,
      label: 'Movie',
      icon: GiFilmStrip,
    },
    {
      id: 26,
      label: 'Tooth',
      icon: GiTooth,
    },
    {
      id: 27,
      label: 'Fix',
      icon: GiTinker,
    },
    {
      id: 28,
      label: 'Meditation',
      icon: GiMeditation,
    },
    {
      id: 29,
      label: 'Orange',
      icon: GiOrangeSlice,
    },
    {
      id: 30,
      label: 'Kitchen',
      icon: GiForkKnifeSpoon,
    },
    {
      id: 31,
      label: 'Guitar',
      icon: GiGuitarBassHead,
    },
    {
      id: 32,
      label: 'Folder',
      icon: GiOpenFolder,
    },
    {
      id: 33,
      label: 'Bars',
      icon: GiNetworkBars,
    },
    {
      id: 34,
      label: 'Money',
      icon: GiTakeMyMoney,
    },
    {
      id: 35,
      label: 'Roller',
      icon: GiPaintRoller,
    },
    {
      id: 36,
      label: 'Palette',
      icon: GiPalette,
    },
  ],
}
